apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - cloudflared-deployment.yaml

patches:
  - target:
      kind: Service
      name: symphony-orchestrator-public
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: symphony-orchestrator-public
  - target:
      kind: Ingress
      name: symphony-orchestrator
    patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: symphony-orchestrator
  - path: system-workloads-patch.yaml
  - path: worker-pool-patch.yaml
