Port 22
Protocol 2
HostKey /etc/ssh/keys/ssh_host_ed25519_key

PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
UsePAM no
PubkeyAuthentication yes

AuthorizedKeysFile /home/symphony/.ssh/authorized_keys
AllowUsers symphony

X11Forwarding no
AllowTcpForwarding no
PermitTunnel no
PrintMotd no
PidFile /run/sshd.pid
