apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: symphony

resources:
  - namespace.yaml
  - orchestrator-deployment.yaml
  - orchestrator-service.yaml
  - orchestrator-public-service.yaml
  - orchestrator-ingress.yaml
  - orchestrator-pdb.yaml
  - orchestrator-workspaces-pvc.yaml
  - worker-headless-service.yaml
  - worker-statefulset.yaml
  - worker-pdb.yaml
  - networkpolicy.yaml

images:
  - name: symphony-orchestrator
    newName: nscr.io/k7qcltdhpncg0/symphony-k8s/orchestrator
    newTag: "20260711-3"
  - name: symphony-worker
    newName: nscr.io/k7qcltdhpncg0/symphony-k8s/worker
    newTag: "20260711-3"
