apiVersion: v1
kind: Service
metadata:
  name: symphony-worker
  namespace: symphony
  labels:
    app: symphony-worker
spec:
  clusterIP: None
  selector:
    app: symphony-worker
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
